# This is a basic workflow to help you get started with Actions

name: Build App

 
on: [push]

 
jobs:
  
  build:
    
    runs-on: windows-latest

    
    steps:
      - uses: actions/checkout@v2
        name: Checkout Code
      - name: install vswhere
        run:  choco install vswhere --pre 
      
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.1
        with:
          vs-version: '[16,16.5)'
        
      
      - name: Run a one-line script
        run: msbuild IAddOneSecondForElder/IAddOneSecondForElder.sln /p:Configuration=Release /p:DeployOnBuild=true /p:PublishProfile=FolderProfile

      
      
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: published_desktopApp
          path: bin\Release\Publish
